version: "3.8"

services:
  wikonnectdb:
    image: postgres:alpine
    env_file: ./env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    networks: 
      - wikonnect
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - wikonnect

networks: 
 wikonnect:
  driver: bridge